// src/data.js
export const products = [
    {
        id: 1,
        name: "Keripik Singkong",
        price: "Rp20.000",
        category: "Makanan",
        description: 'Keripik singkong adalah wujud sempurna dari kesederhanaan yang disulap menjadi kelezatan tiada tara. Berawal dari umbi singkong pilihan yang dibersihkan dan diiris setipis kertas, camilan ini melalui proses penggorengan dengan suhu presisi hingga berubah warna menjadi kuning keemasan yang memikat mata. Saat kepingan tipis itu menyentuh lidah, sensasi pertama yang terasa adalah teksturnya yang begitu garing dan renyah, menciptakan bunyi "kriuk" yang nyaring dan memuaskan di setiap gigitan. Cita rasanya merupakan harmoni yang seimbang antara rasa manis alami dari pati singkong dan gurihnya bumbu bawang putih serta ketumbar yang meresap hingga ke pori-pori terdalam. Entah itu varian rasa original yang asin gurih atau varian balado yang pedas manis dengan lumuran bumbu merah yang lengket, keripik singkong selalu berhasil menghipnotis siapa saja untuk terus mengambilnya lagi dan lagi tanpa henti.',
        images: ["https://placehold.co/600x400/png?text=Keripik1", "https://placehold.co/600x400/png?text=Keripik2", "https://placehold.co/600x400/png?text=Keripik3"], // Nanti ganti path gambar asli
        location: "Kenteng",
        whatsapp: "62812345678", // Nomor WA penjual
    },
    {
        id: 2,
        name: "Kopi Robusta",
        price: "Rp35.000",
        category: "Minuman",
        description: 'Kopi Robusta adalah definisi sejati dari karakter kopi yang tegas, berani, dan tanpa kompromi. Tidak seperti saudaranya yang menawarkan keasaman buah-buahan, Robusta hadir dengan dominasi rasa pahit yang elegan dan body (kekentalan) yang luar biasa tebal memenuhi rongga mulut. Saat diseduh, ia mengeluarkan aroma earthy (tanah) yang khas, bercampur dengan nuansa nutty (kacang-kacangan) dan sentuhan dark chocolate yang pekat. Kandungan kafeinnya yang tinggi—hampir dua kali lipat dari Arabika—memberikan "tendangan" energi instan yang langsung terasa sejak tegukan pertama. Sesuai dengan namanya yang berarti "kuat", setiap cangkir kopi Robusta meninggalkan aftertaste yang panjang dan lekat di lidah, menjadikannya pilihan utama bagi para pencari stimulasi maksimal dan pecinta kopi hitam sejati yang merindukan sensasi rasa klasik yang "nendang".',
        images: ["https://placehold.co/600x400/png?text=Kopi", "https://placehold.co/600x400/png?text=Kopi2", "https://placehold.co/600x400/png?text=Kopi3"],
        location: "Geblug",
        whatsapp: "62898765432",
    },
    {
        id: 3,
        name: "Kain Batik Tulis Motif Alam",
        price: "Rp450.000",
        category: "Kerajinan",
        description: "Kain Batik Tulis ini bukan sekadar selembar kain, melainkan sebuah kanvas yang menceritakan kisah kearifan lokal melalui goresan tangan terampil para pengrajin desa. Dibuat menggunakan canting dan malam panas dengan ketelatenan tinggi, setiap titik dan garis pada motifnya memiliki jiwa yang tidak akan pernah sama antara satu dengan lainnya. Proses pewarnaannya dilakukan secara berulang-ulang untuk menghasilkan gradasi warna yang tajam, awet, dan tidak mudah luntur. Motif alam yang tergambar, mulai dari sulur dedaunan hingga fauna, merepresentasikan hubungan harmonis manusia dengan lingkungan. Kain katun primisima yang digunakan sebagai dasar memberikan sensasi dingin dan lembut di kulit, menjadikannya pilihan busana yang elegan untuk acara formal maupun warisan budaya yang layak dikoleksi.",
        images: ["https://placehold.co/600x400/png?text=Batik1", "https://placehold.co/600x400/png?text=Batik2", "https://placehold.co/600x400/png?text=Batik3"],
        location: "Bendo",
        whatsapp: "62811223344",
    },
    {
        id: 4,
        name: "Gula Aren Murni Organik",
        price: "Rp25.000",
        category: "Makanan",
        description: 'Gula Aren Murni ini dihasilkan dari tetesan nira pohon aren terbaik yang diproses secara tradisional menggunakan tungku kayu, menghasilkan aroma "smoky" yang khas dan otentik. Berbeda dengan gula biasa, gula aren ini memiliki warna cokelat gelap yang pekat dengan tekstur yang padat namun mudah disisir. Rasa manis yang ditawarkan tidak menyengat di tenggorokan, melainkan manis yang legit, lembut, dan sedikit karamelisasi alami. Tanpa campuran bahan pengawet atau pemanis buatan, produk ini sangat aman dikonsumsi dan memiliki indeks glikemik yang lebih rendah, menjadikannya alternatif pemanis yang lebih sehat. Sangat cocok digunakan sebagai pemanis kopi, bahan kue tradisional, atau bumbu masakan nusantara untuk menambah kenikmatan rasa yang mendalam.',
        images: ["https://placehold.co/600x400/png?text=GulaAren1", "https://placehold.co/600x400/png?text=GulaAren2", "https://placehold.co/600x400/png?text=GulaAren3"],
        location: "Bentar",
        whatsapp: "62855667788",
    },
    {
        id: 5,
        name: "Abon Sapi Super Spesial",
        price: "Rp65.000",
        category: "Makanan",
        description: "Abon Sapi Super Spesial adalah definisi kelezatan praktis yang kaya akan rempah nusantara. Terbuat dari daging sapi segar bagian has dalam (tenderloin) yang direbus hingga empuk, lalu disuwir dan dimasak perlahan dengan santan serta bumbu rempah rahasia hingga kering sempurna. Hasilnya adalah serat-serat daging berwarna cokelat keemasan yang renyah namun tetap terasa serat dagingnya saat dikunyah. Perpaduan rasa gurih daging, manisnya gula merah, dan aroma ketumbar serta bawang goreng menciptakan harmoni rasa yang meledak di mulut. Abon ini sangat cocok dijadikan lauk pendamping nasi hangat, isian roti, atau sekadar camilan bergizi tinggi. Dikemas dalam wadah kedap udara untuk menjamin kerenyahan yang tahan lama tanpa bahan pengawet.",
        images: ["https://placehold.co/600x400/png?text=Abon1", "https://placehold.co/600x400/png?text=Abon2", "https://placehold.co/600x400/png?text=Abon3"],
        location: "Cerme",
        whatsapp: "62899001122",
    },
    {
        id: 6,
        name: "Sale Pisang Basah Legit",
        price: "Rp18.000",
        category: "Makanan",
        description: 'Sale Pisang Basah ini merupakan transformasi manis dari buah pisang ambon matang pilihan yang melalui proses pengasapan alami untuk mengurangi kadar air sekaligus mempertahankan nektar manisnya. Berbeda dengan keripik, sale basah memiliki tekstur yang unik: bagian luarnya sedikit kering dan terkaramelisasi dengan warna cokelat mengkilap, sementara bagian dalamnya tetap lembut, kenyal, dan lumer di mulut. Proses pengasapan tradisional memberikan aroma asap yang samar namun sedap, menyeimbangkan rasa manis pisang yang sangat pekat. Camilan ini adalah teman minum teh yang sempurna di sore hari, menawarkan cita rasa nostalgia desa yang kental dan sensasi "chewy" yang membuat ketagihan tanpa rasa bosan.',
        images: ["https://placehold.co/600x400/png?text=SalePisang1", "https://placehold.co/600x400/png?text=SalePisang2", "https://placehold.co/600x400/png?text=SalePisang3"],
        location: "Perampelan I",
        whatsapp: "62877889900",
    },
    {
        id: 7,
        name: "Madu Hutan Liar Murni",
        price: "Rp120.000",
        category: "Minuman",
        description: 'Madu Hutan Liar ini adalah "emas cair" yang dipanen langsung dari sarang lebah Apis dorsata yang hidup bebas di pedalaman hutan, bukan hasil ternak. Diproses secara lestari tanpa melalui pemanasan (raw honey) atau pasteurisasi, madu ini mempertahankan seluruh enzim alami, vitamin, dan propolis yang seringkali hilang pada madu pabrikan. Teksturnya sedikit lebih encer dengan warna gelap yang eksotis, mencerminkan nektar multiflora yang dihisap lebah dari berbagai bunga liar hutan. Rasanya sangat kompleks; perpaduan manis yang kuat, sedikit sentuhan asam fermentasi alami, dan aroma woody yang khas. Setiap tetesnya dipercaya mampu meningkatkan imunitas tubuh dan menjadi obat alami untuk berbagai keluhan kesehatan, menjadikannya suplemen harian yang wajib ada di rumah.',
        images: ["https://placehold.co/600x400/png?text=Madu1", "https://placehold.co/600x400/png?text=Madu2", "https://placehold.co/600x400/png?text=Madu3"],
        location: "Perampelan II",
        whatsapp: "62813456789",
    },
    {
        id: 8,
        name: "Sambal Bawang Ulek Rumahan",
        price: "Rp25.000",
        category: "Makanan",
        description: 'Sambal Bawang ini diciptakan bagi para pecinta pedas yang merindukan cita rasa otentik sambal ulek tangan, bukan blender. Dibuat dari cabai rawit merah "setan" pilihan yang segar dan bawang putih kating yang wangi, sambal ini dimasak dengan teknik *slow cooking* menggunakan minyak kelapa hingga tanak dan berminyak. Teksturnya yang masih kasar memberikan sensasi gigitan cabai asli yang memuaskan. Rasa pedasnya yang menonjok seketika ditenangkan oleh gurihnya bawang dan asin yang pas, menciptakan profil rasa yang sederhana namun mematikan. Sangat cocok sebagai pendamping ayam goreng, tempe hangat, atau bahkan hanya dicampur dengan nasi putih panas sekalipun, sambal ini siap mengubah makanan biasa menjadi hidangan istimewa yang menggugah selera makan.',
        images: ["https://placehold.co/600x400/png?text=Sambal1", "https://placehold.co/600x400/png?text=Sambal2", "https://placehold.co/600x400/png?text=Sambal3"],
        location: "Klumpit",
        whatsapp: "62815678901",
    },
    {
        id: 9,
        name: "Tas Anyaman Eceng Gondok",
        price: "Rp150.000",
        category: "Aksesoris",
        description: "Tas Anyaman Eceng Gondok ini adalah bukti nyata bagaimana kreativitas mampu mengubah tanaman gulma menjadi karya seni bernilai tinggi yang ramah lingkungan. Batang eceng gondok yang telah dikeringkan secara sempurna dianyam dengan ketelitian tinggi oleh pengrajin wanita desa, menghasilkan pola anyaman yang rapat, kuat, dan simetris. Memiliki warna cokelat natural yang memberikan kesan *rustic* dan *bohemian*, tas ini sangat cocok dipadukan dengan gaya busana kasual maupun etnik modern. Permukaannya telah dilapisi dengan vernis *water-based* anti jamur untuk memastikan keawetan tanpa menghilangkan tekstur alami seratnya. Selain modis, menggunakan tas ini berarti turut mendukung pelestarian lingkungan sungai dan pemberdayaan ekonomi pengrajin lokal.",
        images: ["https://placehold.co/600x400/png?text=TasAnyam1", "https://placehold.co/600x400/png?text=TasAnyam2", "https://placehold.co/600x400/png?text=TasAnyam3"],
        location: "Sumberan",
        whatsapp: "62817890123",
    },
    {
        id: 10,
        name: "Wedang Uwuh Instan",
        price: "Rp35.000",
        category: "Minuman",
        description: 'Wedang Uwuh, yang secara harfiah berarti "minuman sampah" dalam bahasa Jawa, adalah warisan leluhur yang menyimpan segudang khasiat di balik penampilannya yang unik. Produk ini mengemas racikan dedaunan dan rempah kering asli—terdiri dari serutan kayu secang, jahe emprit, cengkeh, kayu manis, daun pala, dan kapulaga—dalam kemasan praktis siap seduh. Saat disiram air panas, air akan berubah menjadi merah rubi cantik berkat kayu secang, menyebarkan aroma rempah yang menenangkan jiwa. Rasanya adalah perpaduan hangat pedas dari jahe, manis dari gula batu, dan segar rempah yang menyegarkan tenggorokan. Minuman ini sangat ampuh untuk menghangatkan tubuh, meredakan masuk angin, dan melancarkan peredaran darah, membawa suasana angkringan Jogja langsung ke cangkir Anda.',
        images: ["https://placehold.co/600x400/png?text=Wedang1", "https://placehold.co/600x400/png?text=Wedang2", "https://placehold.co/600x400/png?text=Wedang3"],
        location: "Kenteng",
        whatsapp: "62819012345",
    },
];
